import React from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

// Removed: Next.js layout — using Vite/React instead.
// Keep minimal export to avoid import errors from any stray references.

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
