services:
  backend:
    build:
      context: ./backend
      # use the builder stage which installs devDependencies (ts-node-dev)
      target: builder
    working_dir: /app
    command: npm run dev
    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
    ports:
      - "4000:3002"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://habitflow:secret@db:5432/habitflow_dev

  frontend:
    image: node:18
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/usr/src/app:delegated
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
