name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  package-ci:
    name: CI — ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [frontend, backend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm and node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ matrix.package }}/node_modules
          key: ${{ runner.os }}-node-${{ matrix.package }}-${{ hashFiles(format('{0}/package-lock.json', matrix.package)) }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.package }}-

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.package }}

      - name: Lint
        run: npm run lint --if-present
        working-directory: ${{ matrix.package }}

      - name: Build
        run: npm run build --if-present
        working-directory: ${{ matrix.package }}

      - name: Test
        run: npm test --if-present
        working-directory: ${{ matrix.package }}
